import { z } from "zod"

export const branchSchema = z.object({
    id: z.number(),
    branchName: z.string(),
    branchCode: z.string(),
    physicalAddress: z.object({
        street: z.string(),
        city: z.string(),
        state: z.string(),
        postalCode: z.string(),
        country: z.string(),
    }),
    billingAddress: z.object({
        street: z.string(),
        city: z.string(),
        state: z.string(),
        postalCode: z.string(),
        country: z.string(),
    }),
    operationHours: z.object({
        days: z.string(), // e.g., "Monday - Friday"
        hours: z.string(), // e.g., "9:00 AM - 5:00 PM"
    }),
    phone: z.string(),
    email: z.string(),
    employees: z.number(),
    status: z.enum(["active", "inactive"]),
})

export const userSchema = z.object({
    id: z.number(),
    firstName: z.string(),
    lastName: z.string(),
    nickname: z.string().optional(),
    position: z.string(),
    phone: z.string(),
    userCode: z.string(),
    status: z.enum(["active", "inactive", "pending", "expired"]),
})

export const companySchema = z.object({
    id: z.number(),
    logo: z.string(),
    companyName: z.string(),
    registrationNumber: z.string(),
    employees: z.number(),
    branches: z.number(),
    tokenUsage: z.number(),
    registeredAt: z.string(),
    status: z.enum(["active", "inactive"]),
    physicalAddress: z.object({
        street: z.string(),
        city: z.string(),
        state: z.string(),
        postalCode: z.string(),
        country: z.string(),
        phone: z.string(),
    }),
    billingAddress: z.object({
        street: z.string(),
        city: z.string(),
        state: z.string(),
        postalCode: z.string(),
        country: z.string(),
        phone: z.string(),
    }),
})

export const companyData: z.infer<typeof companySchema>[] = [
    {
        id: 1,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=TechCorp&backgroundColor=4F46E5",
        companyName: "TechCorp Solutions",
        registrationNumber: "REG-2023-001247",
        employees: 1247,
        branches: 12,
        tokenUsage: 2847563,
        registeredAt: "2023-03-15",
        status: "active" as const,
        physicalAddress: {
            street: "123 Tech Avenue, Suite 400",
            city: "San Francisco",
            state: "California",
            postalCode: "94102",
            country: "United States",
            phone: "+1 (415) 555-0123",
        },
        billingAddress: {
            street: "123 Tech Avenue, Suite 400",
            city: "San Francisco",
            state: "California",
            postalCode: "94102",
            country: "United States",
            phone: "+1 (415) 555-0123",
        },
    },
    {
        id: 2,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=GlobalInnovations&backgroundColor=059669",
        companyName: "Global Innovations Inc",
        registrationNumber: "REG-2022-002834",
        employees: 2834,
        branches: 24,
        tokenUsage: 5293847,
        registeredAt: "2022-11-08",
        status: "active" as const,
        physicalAddress: {
            street: "456 Innovation Drive",
            city: "New York",
            state: "New York",
            postalCode: "10001",
            country: "United States",
            phone: "+1 (212) 555-0234",
        },
        billingAddress: {
            street: "789 Finance Street",
            city: "New York",
            state: "New York",
            postalCode: "10002",
            country: "United States",
            phone: "+1 (212) 555-0235",
        },
    },
    {
        id: 3,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=DigitalWave&backgroundColor=DC2626",
        companyName: "Digital Wave Media",
        registrationNumber: "REG-2024-000456",
        employees: 456,
        branches: 5,
        tokenUsage: 892456,
        registeredAt: "2024-01-20",
        status: "inactive" as const,
        physicalAddress: {
            street: "789 Media Boulevard",
            city: "Los Angeles",
            state: "California",
            postalCode: "90001",
            country: "United States",
            phone: "+1 (213) 555-0345",
        },
        billingAddress: {
            street: "321 Accounting Lane",
            city: "Los Angeles",
            state: "California",
            postalCode: "90002",
            country: "United States",
            phone: "+1 (213) 555-0346",
        },
    },
    {
        id: 4,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=CloudNine&backgroundColor=9333EA",
        companyName: "CloudNine Technologies",
        registrationNumber: "REG-2022-003421",
        employees: 3421,
        branches: 18,
        tokenUsage: 7234891,
        registeredAt: "2022-07-12",
        status: "active" as const,
        physicalAddress: {
            street: "321 Cloud Street, Floor 9",
            city: "Seattle",
            state: "Washington",
            postalCode: "98101",
            country: "United States",
            phone: "+1 (206) 555-0456",
        },
        billingAddress: {
            street: "555 Billing Plaza",
            city: "Seattle",
            state: "Washington",
            postalCode: "98102",
            country: "United States",
            phone: "+1 (206) 555-0457",
        },
    },
    {
        id: 5,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=NextGen&backgroundColor=EA580C",
        companyName: "NextGen Enterprises",
        registrationNumber: "REG-2023-000892",
        employees: 892,
        branches: 8,
        tokenUsage: 1456782,
        registeredAt: "2023-09-05",
        status: "active" as const,
        physicalAddress: {
            street: "555 Enterprise Plaza",
            city: "Austin",
            state: "Texas",
            postalCode: "73301",
            country: "United States",
            phone: "+1 (512) 555-0567",
        },
        billingAddress: {
            street: "888 Invoice Avenue",
            city: "Austin",
            state: "Texas",
            postalCode: "73302",
            country: "United States",
            phone: "+1 (512) 555-0568",
        },
    },
    {
        id: 6,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=SmartSystems&backgroundColor=0891B2",
        companyName: "Smart Systems Ltd",
        registrationNumber: "REG-2023-000634",
        employees: 634,
        branches: 6,
        tokenUsage: 1123490,
        registeredAt: "2023-06-18",
        status: "active" as const,
        physicalAddress: {
            street: "888 Systems Road",
            city: "Boston",
            state: "Massachusetts",
            postalCode: "02101",
            country: "United States",
            phone: "+1 (617) 555-0678",
        },
        billingAddress: {
            street: "222 Payment Street",
            city: "Boston",
            state: "Massachusetts",
            postalCode: "02102",
            country: "United States",
            phone: "+1 (617) 555-0679",
        },
    },
    {
        id: 7,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=FutureVision&backgroundColor=7C3AED",
        companyName: "Future Vision Group",
        registrationNumber: "REG-2024-000178",
        employees: 178,
        branches: 3,
        tokenUsage: 234567,
        registeredAt: "2024-02-28",
        status: "inactive" as const,
        physicalAddress: {
            street: "222 Vision Way",
            city: "Denver",
            state: "Colorado",
            postalCode: "80201",
            country: "United States",
            phone: "+1 (303) 555-0789",
        },
        billingAddress: {
            street: "444 Financial Boulevard",
            city: "Denver",
            state: "Colorado",
            postalCode: "80202",
            country: "United States",
            phone: "+1 (303) 555-0790",
        },
    },
    {
        id: 8,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=DataDynamics&backgroundColor=DB2777",
        companyName: "Data Dynamics Corp",
        registrationNumber: "REG-2022-001567",
        employees: 1567,
        branches: 14,
        tokenUsage: 3678912,
        registeredAt: "2022-12-03",
        status: "active" as const,
        physicalAddress: {
            street: "999 Data Center Lane",
            city: "Chicago",
            state: "Illinois",
            postalCode: "60601",
            country: "United States",
            phone: "+1 (312) 555-0890",
        },
        billingAddress: {
            street: "777 Accounts Payable Drive",
            city: "Chicago",
            state: "Illinois",
            postalCode: "60602",
            country: "United States",
            phone: "+1 (312) 555-0891",
        },
    },
    {
        id: 9,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=AlphaVentures&backgroundColor=059669",
        companyName: "Alpha Ventures",
        registrationNumber: "REG-2023-002145",
        employees: 2145,
        branches: 16,
        tokenUsage: 4892341,
        registeredAt: "2023-04-22",
        status: "active" as const,
        physicalAddress: {
            street: "777 Venture Capital Street",
            city: "Miami",
            state: "Florida",
            postalCode: "33101",
            country: "United States",
            phone: "+1 (305) 555-0901",
        },
        billingAddress: {
            street: "333 Receivables Road",
            city: "Miami",
            state: "Florida",
            postalCode: "33102",
            country: "United States",
            phone: "+1 (305) 555-0902",
        },
    },
    {
        id: 10,
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=InnovateLabs&backgroundColor=4F46E5",
        companyName: "Innovate Labs",
        registrationNumber: "REG-2024-000423",
        employees: 423,
        branches: 4,
        tokenUsage: 678234,
        registeredAt: "2024-05-10",
        status: "active" as const,
        physicalAddress: {
            street: "111 Innovation Park",
            city: "Portland",
            state: "Oregon",
            postalCode: "97201",
            country: "United States",
            phone: "+1 (503) 555-0912",
        },
        billingAddress: {
            street: "666 Payroll Parkway",
            city: "Portland",
            state: "Oregon",
            postalCode: "97202",
            country: "United States",
            phone: "+1 (503) 555-0913",
        },
    },
];

// Branch data mapped by company ID
export const branchDataByCompany: Record<number, z.infer<typeof branchSchema>[]> = {
    1: [
        {
            id: 101,
            branchName: "San Francisco Headquarters",
            branchCode: "SF-HQ",
            physicalAddress: {
                street: "123 Tech Avenue, Suite 400",
                city: "San Francisco",
                state: "California",
                postalCode: "94102",
                country: "United States",
            },
            billingAddress: {
                street: "123 Tech Avenue, Suite 400",
                city: "San Francisco",
                state: "California",
                postalCode: "94102",
                country: "United States",
            },
            operationHours: {
                days: "Monday - Friday",
                hours: "9:00 AM - 6:00 PM",
            },
            phone: "+1 (415) 555-0123",
            email: "sf.hq@techcorp.com",
            employees: 245,
            status: "active" as const,
        },
        {
            id: 102,
            branchName: "San Jose Branch",
            branchCode: "SJ-01",
            physicalAddress: {
                street: "456 Valley Road",
                city: "San Jose",
                state: "California",
                postalCode: "95110",
                country: "United States",
            },
            billingAddress: {
                street: "123 Tech Avenue, Suite 400",
                city: "San Francisco",
                state: "California",
                postalCode: "94102",
                country: "United States",
            },
            operationHours: {
                days: "Monday - Friday",
                hours: "8:00 AM - 5:00 PM",
            },
            phone: "+1 (408) 555-0234",
            email: "sj.branch@techcorp.com",
            employees: 87,
            status: "active" as const,
        },
        {
            id: 103,
            branchName: "Oakland Office",
            branchCode: "OAK-01",
            physicalAddress: {
                street: "789 Broadway Street",
                city: "Oakland",
                state: "California",
                postalCode: "94612",
                country: "United States",
            },
            billingAddress: {
                street: "123 Tech Avenue, Suite 400",
                city: "San Francisco",
                state: "California",
                postalCode: "94102",
                country: "United States",
            },
            operationHours: {
                days: "Monday - Saturday",
                hours: "10:00 AM - 7:00 PM",
            },
            phone: "+1 (510) 555-0345",
            email: "oakland@techcorp.com",
            employees: 52,
            status: "active" as const,
        },
    ],
    2: [
        {
            id: 201,
            branchName: "New York Headquarters",
            branchCode: "NY-HQ",
            physicalAddress: {
                street: "456 Innovation Drive",
                city: "New York",
                state: "New York",
                postalCode: "10001",
                country: "United States",
            },
            billingAddress: {
                street: "456 Innovation Drive",
                city: "New York",
                state: "New York",
                postalCode: "10001",
                country: "United States",
            },
            operationHours: {
                days: "Monday - Friday",
                hours: "8:00 AM - 6:00 PM",
            },
            phone: "+1 (212) 555-0234",
            email: "ny.hq@globalinnovations.com",
            employees: 456,
            status: "active" as const,
        },
        {
            id: 202,
            branchName: "Brooklyn Branch",
            branchCode: "BKN-01",
            physicalAddress: {
                street: "123 Atlantic Avenue",
                city: "Brooklyn",
                state: "New York",
                postalCode: "11217",
                country: "United States",
            },
            billingAddress: {
                street: "456 Innovation Drive",
                city: "New York",
                state: "New York",
                postalCode: "10001",
                country: "United States",
            },
            operationHours: {
                days: "Monday - Friday",
                hours: "9:00 AM - 5:00 PM",
            },
            phone: "+1 (718) 555-0456",
            email: "brooklyn@globalinnovations.com",
            employees: 134,
            status: "active" as const,
        },
    ],
    3: [
        {
            id: 301,
            branchName: "Los Angeles Main",
            branchCode: "LA-MAIN",
            physicalAddress: {
                street: "789 Media Boulevard",
                city: "Los Angeles",
                state: "California",
                postalCode: "90001",
                country: "United States",
            },
            billingAddress: {
                street: "789 Media Boulevard",
                city: "Los Angeles",
                state: "California",
                postalCode: "90001",
                country: "United States",
            },
            operationHours: {
                days: "Monday - Friday",
                hours: "9:00 AM - 5:00 PM",
            },
            phone: "+1 (213) 555-0345",
            email: "la.main@digitalwave.com",
            employees: 178,
            status: "inactive" as const,
        },
        {
            id: 302,
            branchName: "Santa Monica Office",
            branchCode: "SM-01",
            physicalAddress: {
                street: "321 Ocean Avenue",
                city: "Santa Monica",
                state: "California",
                postalCode: "90401",
                country: "United States",
            },
            billingAddress: {
                street: "789 Media Boulevard",
                city: "Los Angeles",
                state: "California",
                postalCode: "90001",
                country: "United States",
            },
            operationHours: {
                days: "Tuesday - Saturday",
                hours: "10:00 AM - 6:00 PM",
            },
            phone: "+1 (310) 555-0567",
            email: "santamonica@digitalwave.com",
            employees: 89,
            status: "inactive" as const,
        },
    ],
};

// User data mapped by company ID
export const userDataByCompany: Record<number, z.infer<typeof userSchema>[]> = {
    1: [
        {
            id: 1001,
            firstName: "John",
            lastName: "Smith",
            nickname: "Johnny",
            position: "Chief Technology Officer",
            phone: "+1 (415) 555-1001",
            userCode: "0001",
            status: "active" as const,
        },
        {
            id: 1002,
            firstName: "Sarah",
            lastName: "Johnson",
            nickname: "SJ",
            position: "Senior Software Engineer",
            phone: "+1 (415) 555-1002",
            userCode: "0002",
            status: "active" as const,
        },
        {
            id: 1003,
            firstName: "Michael",
            lastName: "Chen",
            position: "Product Manager",
            phone: "+1 (415) 555-1003",
            userCode: "0003",
            status: "active" as const,
        },
        {
            id: 1004,
            firstName: "Emily",
            lastName: "Rodriguez",
            nickname: "Em",
            position: "UX Designer",
            phone: "+1 (415) 555-1004",
            userCode: "0004",
            status: "pending" as const,
        },
        {
            id: 1005,
            firstName: "David",
            lastName: "Kim",
            position: "DevOps Engineer",
            phone: "+1 (415) 555-1005",
            userCode: "0005",
            status: "inactive" as const,
        },
        {
            id: 1006,
            firstName: "Jessica",
            lastName: "Taylor",
            nickname: "Jess",
            position: "Marketing Director",
            phone: "+1 (415) 555-1006",
            userCode: "0006",
            status: "expired" as const,
        },
    ],
    2: [
        {
            id: 2001,
            firstName: "Robert",
            lastName: "Williams",
            nickname: "Rob",
            position: "CEO",
            phone: "+1 (212) 555-2001",
            userCode: "0001",
            status: "active" as const,
        },
        {
            id: 2002,
            firstName: "Amanda",
            lastName: "Brown",
            position: "Chief Financial Officer",
            phone: "+1 (212) 555-2002",
            userCode: "0002",
            status: "active" as const,
        },
        {
            id: 2003,
            firstName: "James",
            lastName: "Davis",
            nickname: "Jim",
            position: "Operations Manager",
            phone: "+1 (212) 555-2003",
            userCode: "0003",
            status: "pending" as const,
        },
    ],
    3: [
        {
            id: 3001,
            firstName: "Lisa",
            lastName: "Anderson",
            position: "Creative Director",
            phone: "+1 (213) 555-3001",
            userCode: "0001",
            status: "inactive" as const,
        },
        {
            id: 3002,
            firstName: "Chris",
            lastName: "Martinez",
            nickname: "CM",
            position: "Video Editor",
            phone: "+1 (213) 555-3002",
            userCode: "0002",
            status: "inactive" as const,
        },
    ],
};